services:
  devops-wiki:
    image: aprozzo/devops-wiki:latest   
    pull_policy: always                  
    container_name: devops-wiki
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"              